### ISSUE TITLE
Wrong transfer target Awebb/nina

### ISSUE THREAD

**Issue by Awebb** [awebb-sessiondigital/nina#1]
Greetings! It appears you tried to transfer one of your projects to my github account. I let the transfer expire, but I'm not sure what you want me to do with it. I can also not find a message system on github, so here comes a bug report.

**Comment by awebb-sessiondigital** [comment]
My apologies, I accidentally pressed enter without completing the entire username and cancelled shortly afterwards. Sorry for any inconvenience. Thanks
